import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — InterviewAI',
  description: 'The legal agreement governing your use of the InterviewAI platform.',
}

const sections = [
  {
    id: 'acceptance',
    label: '01 — Acceptance of Terms',
    content: [
      {
        heading: 'Agreement',
        body: 'By accessing or using InterviewAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service. These Terms constitute a binding agreement between you and InterviewAI.',
      },
      {
        heading: 'Eligibility',
        body: 'You must be at least 13 years of age to use the Service. By using InterviewAI, you represent that you meet this age requirement and have the legal capacity to enter into this agreement.',
      },
      {
        heading: 'Changes to Terms',
        body: 'We may update these Terms from time to time. We will notify you of material changes via email or a prominent notice on the platform at least 7 days before changes take effect. Continued use of the Service after changes constitutes acceptance.',
      },
    ],
  },
  {
    id: 'service-description',
    label: '02 — Service Description',
    content: [
      {
        heading: 'What InterviewAI Provides',
        body: 'InterviewAI is an AI-powered technical interview practice platform. We provide simulated coding interviews, real-time AI feedback, performance analytics, and personalised study roadmaps.',
      },
      {
        heading: 'AI-Generated Content',
        body: 'Interview questions and feedback are generated by AI models. While we strive for accuracy and quality, AI-generated content may not always be error-free. InterviewAI does not guarantee that practice sessions will lead to successful real-world interviews.',
      },
      {
        heading: 'Service Availability',
        body: 'We aim for 99.5% monthly uptime but do not guarantee uninterrupted access. Scheduled maintenance, updates, or events beyond our control may cause temporary downtime. We will provide advance notice for planned maintenance where possible.',
      },
    ],
  },
  {
    id: 'payments',
    label: '03 — Payments & Subscriptions',
    content: [
      {
        heading: 'Free Plan',
        body: 'The Free plan includes 3 AI practice interviews per month. Free features may be changed or limited at our discretion with 30 days\' notice.',
      },
      {
        heading: 'Pro Plan',
        body: 'The Pro plan is priced at ₹299/month (or ₹2,990/year). Subscriptions auto-renew unless cancelled. All payments are processed by Razorpay and subject to their terms.',
      },
      {
        heading: 'Cancellation & Refunds',
        body: 'You may cancel your Pro subscription at any time. Cancellation takes effect at the end of the current billing period — you retain access until then. We offer a 7-day refund for new subscriptions if you have not used more than 1 Pro interview session.',
      },
      {
        heading: 'Taxes',
        body: 'Prices are exclusive of applicable GST. GST will be added at checkout based on your billing address.',
      },
    ],
  },
  {
    id: 'user-obligations',
    label: '04 — Your Obligations',
    content: [
      {
        heading: 'Acceptable Use',
        body: 'You agree to use the Service only for lawful purposes and in accordance with these Terms. You may not: (a) violate any applicable laws; (b) attempt to reverse-engineer or extract the AI model weights; (c) use automated tools to scrape or bulk-download content; (d) share your account credentials with others.',
      },
      {
        heading: 'Account Security',
        body: 'You are responsible for maintaining the security of your account credentials. Notify us immediately at support@interviewai.app if you suspect unauthorised access.',
      },
      {
        heading: 'User Content',
        body: 'By uploading a resume or submitting answers, you grant InterviewAI a limited, non-exclusive licence to process that content solely for delivering the Service to you. We do not sell or share your interview answers.',
      },
    ],
  },
  {
    id: 'intellectual-property',
    label: '05 — Intellectual Property',
    content: [
      {
        heading: 'Our Content',
        body: 'The InterviewAI platform, including its AI models, question database, UI, and code, is owned by InterviewAI and protected by copyright and other intellectual property laws.',
      },
      {
        heading: 'Your Data',
        body: 'You retain ownership of any content you upload (resumes, code submissions). You grant us a licence to process this content as necessary to provide the Service.',
      },
    ],
  },
  {
    id: 'termination',
    label: '06 — Termination',
    content: [
      {
        heading: 'By You',
        body: 'You may delete your account at any time from Account Settings. Upon deletion, your personal data will be removed within 30 days (subject to legal retention requirements).',
      },
      {
        heading: 'By Us',
        body: 'We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behaviour, or attempt to harm the platform or other users. Material violations may result in immediate termination without refund.',
      },
    ],
  },
  {
    id: 'disclaimers',
    label: '07 — Disclaimers & Limitations',
    content: [
      {
        heading: 'As-Is Service',
        body: 'The Service is provided "as is" without warranties of any kind, express or implied, including merchantability or fitness for a particular purpose.',
      },
      {
        heading: 'Limitation of Liability',
        body: 'To the maximum extent permitted by law, InterviewAI\'s total liability to you for any claims arising from these Terms or the Service shall not exceed the amount you paid us in the 3 months preceding the claim.',
      },
      {
        heading: 'Governing Law',
        body: 'These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka.',
      },
    ],
  },
  {
    id: 'contact',
    label: '08 — Contact',
    content: [
      {
        heading: 'Legal Inquiries',
        body: 'For legal questions, notices, or support: legal@interviewai.app. We respond within 72 hours on business days.',
      },
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="max-w-[900px] mx-auto px-6 py-16">
      {/* Header */}
      <div className="mb-14">
        <p className="font-mono text-[10px] text-[#818cf8] uppercase tracking-[0.2em] mb-3">
          // LEGAL
        </p>
        <h1 className="font-display text-[44px] font-bold text-white tracking-[-0.025em] leading-[1.05] mb-4">
          Terms of Service
        </h1>
        <p className="font-body text-[15px] text-[#9ca3af] max-w-[560px]">
          Please read these Terms carefully before using InterviewAI. They form the legal
          agreement between you and us.
        </p>
        <div className="mt-6 flex items-center gap-3">
          <span className="inline-flex items-center gap-1.5 font-mono text-[10px] text-[#64748b] uppercase tracking-[0.08em] border border-[#1e1e2f] rounded-[4px] px-2.5 py-1">
            <span className="h-1.5 w-1.5 rounded-full bg-[#6366f1]" />
            Last updated: September 2026
          </span>
          <span className="inline-flex items-center gap-1.5 font-mono text-[10px] text-[#64748b] uppercase tracking-[0.08em] border border-[#1e1e2f] rounded-[4px] px-2.5 py-1">
            Effective: September 20, 2026
          </span>
        </div>
      </div>

      {/* Quick nav */}
      <nav className="mb-12 p-5 border border-[#1e1e2f] rounded-[6px] bg-[#09090e]">
        <p className="font-mono text-[10px] text-[#64748b] uppercase tracking-[0.12em] mb-3">
          Contents
        </p>
        <ul className="space-y-1.5">
          {sections.map((s) => (
            <li key={s.id}>
              <a
                href={`#${s.id}`}
                className="font-mono text-[12px] text-[#9ca3af] hover:text-[#818cf8] transition-colors uppercase tracking-[0.06em]"
              >
                {s.label}
              </a>
            </li>
          ))}
        </ul>
      </nav>

      {/* Sections */}
      <div className="space-y-14">
        {sections.map((section) => (
          <section key={section.id} id={section.id}>
            <h2 className="font-mono text-[13px] text-[#818cf8] uppercase tracking-[0.12em] mb-6 border-b border-[#1e1e2f] pb-3">
              {section.label}
            </h2>
            <div className="space-y-6">
              {section.content.map((item) => (
                <div key={item.heading} className="pl-4 border-l border-[#1e1e2f]">
                  <h3 className="font-mono text-[12px] font-bold text-white uppercase tracking-[0.08em] mb-2">
                    {item.heading}
                  </h3>
                  <p className="font-body text-[14px] text-[#9ca3af] leading-[1.75]">
                    {item.body}
                  </p>
                </div>
              ))}
            </div>
          </section>
        ))}
      </div>

      {/* Bottom CTA */}
      <div className="mt-16 p-6 border border-[#1e1e2f] rounded-[6px] bg-[#09090e] text-center">
        <p className="font-mono text-[11px] text-[#9ca3af] mb-1">
          Legal questions or notices?
        </p>
        <a
          href="mailto:legal@interviewai.app"
          className="font-mono text-[12px] text-[#818cf8] hover:text-white transition-colors uppercase tracking-[0.06em]"
        >
          legal@interviewai.app →
        </a>
      </div>
    </div>
  )
}
